config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  resources 'original_tables'
  resources 'mypage', only: %i(index)
  resources 'chat_system_authentication_tokens', only: %i(new create destroy)
  resources 'chat_system_authentication_mails', only: %i(destroy)
  get '/chat_system_links/:token', to: 'chat_system_links#create', as: 'chat_system_links'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_description_token.html.erb
<div>
  <h3>チャットシステムとの連携方法</h3>
  <ol>
    <li>トークンを発行します</li>
    <li>アカウント認証コマンドとともにチャットで発言します</li>
    <li>アカウント作成時に登録したメールアドレスへ、確認が送られます</li>
    <li>メールアドレスに書かれた承認リンクにアクセスします</li>
    <li>トークンが発言されたチャット環境のチャットアカウントと本サービスのアカウントが紐付けられます</li>
  </ol>
</div>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-md navbar-static-top bg-light navbar-light">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">CD2C - Card Deck Create and Drow for Chat</a>

      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    </div>
    <div id="bs-navbar-collapse-1" class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item"><%= link_to('マイページ', mypage_index_path) %></a>
              <a class="dropdown-item"><%= link_to('利用者情報の編集', edit_user_registration_path) %></a>
              <a class="dropdown-item"><%= link_to('ログアウト', destroy_user_session_path, method: :delete) %></a>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to('ログイン', new_user_session_path, class: 'nav-link') %></li>
          <li class="nav-item active"><%= link_to('新規登録', new_user_registration_path, class: 'nav-link') %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>