config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  resources 'original_tables'
  resources 'mypage', only: %i(index)
  resources 'chat_system_authentication_tokens', only: %i(new create destroy)
  resources 'chat_system_authentication_mails', only: %i(destroy)
  get '/chat_system_links/:token', to: 'chat_system_links#create', as: 'chat_system_links'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/original_tables_controller.rb
class OriginalTablesController < ApplicationController
  before_action :require_sign_in, only: %i(new create edit update destroy)

  def index
    @original_tables = OriginalTable.public?(current_user&.id)
  end

  def new
    @original_table = OriginalTable.new
  end

  def create
    @original_table = OriginalTable.new(params_for_create)
    @original_table.user = current_user

    if @original_table.save
      flash[:success] = t('views.flash.added_original_table')
      redirect_to(original_table_path(@original_table))
    else
      render(:new)
    end
  end

  def edit
    @original_table = OriginalTable.find(params[:id])

    unless(@original_table.user == current_user)
      flash[:abort] = t('views.flash.edit_original_table_can_author_only')
      redirect_to(original_table_path(@original_table))
    end
  end

  def show
    @original_table = OriginalTable.find(params[:id])

    unless(@original_table.public || @original_table.user == current_user)
      flash[:abort] = t('views.flash.show_original_table_can_author_only')
      redirect_to(original_tables_path)
    end
  end

  def update
    @original_table = OriginalTable.find(params[:id])

    unless(@original_table.user == current_user)
      flash[:abort] = t('views.flash.edit_original_table_can_author_only')
      redirect_to(original_table_path(@original_table))
    end

    if(@original_table.update(params_for_update))
      flash[:success] = t('views.flash.updated_original_table')
      redirect_to(original_table_path(@original_table))
    else
      render(:edit)
    end
  end

  def destroy
    @original_table = OriginalTable.find(params[:id])

    unless(@original_table.user == current_user)
      flash[:abort] = t('views.flash.edit_original_table_can_author_only')
      redirect_to(original_table_path(@original_table))
    end

    if(@original_table.destroy)
      flash[:success] = t('views.flash.deleted_original_table')
      redirect_to(original_tables_path)
    else
      render(:show)
    end
  end

  private

  def params_for_create
    params.
      require(:original_table).
      permit(:name, :definition, :public)
  end

  def params_for_update
    params.
      require(:original_table).
      permit(:definition, :public)
  end
end

app/helpers/original_tables_helper.rb
module OriginalTablesHelper
end

app/views/original_tables/_form.html.erb
<%= form_for(@original_table) do |f| %>
  <div class="form-group">
    <%= f.label(:name, for: 'inputName') %>
    <% if name_changeable %>
      <%= f.text_field(:name, class: 'form-control', required: true, id: 'inputName') %>
    <% else %>
      <%= f.text_field(:name, class: 'form-control-plaintext', readonly: true, id: 'inputName', 'aria-describedby': 'nameHelpBlock') %>
      <div class="form-text" id="nameHelpBlock">表の名前を変更することは出来ません。</div>
    <% end %>
  </div>

  <div class="form-check">
    <%= f.check_box(:public, class: 'form-check-input', id: 'checkPublic') %>
    <%= f.label(:public, class: 'form-check-label', for: 'checkPublic', 'aria-descrivedby': 'publicHelpBlock') %>
    <div class="form-text" id="publicHelpBlock">他の利用者にも使用可能にするにはチェックを入れてください。</div>
  </div>

  <div class="form-group">
    <%= f.label(:definition, for: 'textDefinition') %>
    <%= f.text_area(:definition, class: 'form-control', rows: 10, required: true, id: 'textDefinition', 'aria-describedby': 'definitionHelpBlock') %>
    <div class="form-text" id="definitionHelpBlock">1行に表の1項目を書いてください。</div>
  </div>

  <div class="form-group">
    <%= f.submit(class: 'btn btn-success') %>
  </div>
<% end %>

app/views/original_tables/edit.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-xs-12">
      <div class="main-panel">
        <div class="panel-body">
          <%= render('shared/flash') %>

          <div class="page-header">
            <h1>オリジナル表編集</h1>
          </div>

          <%= render('form', name_changeable: false) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/original_tables/index.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-xs-12">
      <div class="main-panel">
        <div class="panel-body">
          <%= render('shared/flash') %>

          <div class="page-header">
            <h1>オリジナル表</h1>
          </div>

          <% if(user_signed_in?) %>
            <p><%= link_to('新規作成', new_original_table_path, class: 'btn btn-responsible btn-success') %></p>
          <% end %>

          <table class="table table-striped original-table-list">
            <thead>
              <tr>
                <th>名前</th>
                <th>作者</th>
                <th>最終更新日</th>
                <th>公開状態</th>
              </tr>
            </thead>
            <tbody>
              <% @original_tables.each do |original_table| %>
                <tr>
                  <td><%= link_to(original_table.name, original_table) %></td>
                  <td><%= original_table.user.username %></td>
                  <td><%= original_table.updated_at %></td>
                  <td><%= original_table.public ? '公開中' : '非公開' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/original_tables/new.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-md-offset-2">
      <div class="main-panel">
        <div class="panel-body">
          <h2>オリジナル表の作成</h2>
          <%= render('form', name_changeable: true) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/original_tables/show.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-xs-12">
      <div class="main-panel">
        <div class="panel-body">
          <%= render('shared/flash') %>

          <div class="page-header">
            <h1>オリジナル表情報</h1>
          </div>

          <table class="table table-striped">
            <tbody>
              <tr>
                <th>名前</th>
                <td><%= @original_table.name %></td>
              </tr>
              <tr>
                <th>作者</th>
                <td><%= @original_table.user.username %></td>
              </tr>
              <tr>
                <th>公開状態</th>
                <td><%= @original_table.public ? '公開中' : '非公開' %></td>
              </tr>
              <tr>
                <th>作成日</th>
                <td><%= @original_table.created_at %></td>
              </tr>
              <tr>
                <th>最終更新日</th>
                <td><%= @original_table.updated_at %></td>
              </tr>
            </tbody>
          </table>

          <h2>表の中身</h2>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>番号</th>
                <th>項目</th>
              </tr>
            </thead>
            <tbody>
              <% i = 0 %>
              <% @original_table.elements.each do |element| %>
                <tr>
                  <td><%= i += 1 %></td>
                  <td><%= element %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <% if(@original_table.user == current_user) %>
            <p>
              <%= link_to('編集', edit_original_table_path, class: 'btn btn-responsible btn-success') %>
              <%= link_to('削除', original_table_path, method: :delete, class: 'btn btn-responsible btn-danger') %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>