config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  resources 'original_tables'
  resources 'mypage', only: %i(index)
  resources 'chat_system_authentication_tokens', only: %i(new create destroy)
  resources 'chat_system_authentication_mails', only: %i(destroy)
  get '/chat_system_links/:token', to: 'chat_system_links#create', as: 'chat_system_links'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :require_sign_in

  def index
    @user = User.find(current_user.id)
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/index.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-md-offset-2">
      <div class="main-panel">
        <div class="panel-body">
          <%= render('shared/flash') %>

          <h1>マイページ</h1>
          <div>
            <p>ユーザー名: <%= @user.username %></p>
            <p>メールアドレス: <%= @user.email %></p>
            <p><%= link_to('ユーザー情報の編集', edit_user_registration_path, class: 'btn btn-success') %></p>
          </div>

          <div>
            <h2>連携しているチャット環境</h2>
            <table class="table table-striped table-responsive">
              <thead>
                <tr>
                  <th>チャット環境</th>
                  <th>サーバ</th>
                  <th>アカウント</th>
                  <th>連携日</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @user.chat_system_links.each do |link| %>
                  <tr>
                    <td><%= link.chat_system.name %></td>
                    <td><%= link.server %></td>
                    <td><%= link.account %></td>
                    <td><%= link.created_at %></td>
                    <td><%= link_to('削除', '#', method: :delete, class: 'btn btn-danger') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div>
            <h2>有効な連携用トークン</h2>
            <table class="table table-striped table-responsive">
              <thead>
                <tr>
                  <th>チャット環境</th>
                  <th>トークン</th>
                  <th>有効期限</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @user.chat_system_authentication_tokens.each do |token| %>
                  <tr>
                    <td><%= token.chat_system.name %></td>
                    <td><input type="text" value="<%= token.token %>"></td>
                    <td><%= token.expire_at %></td>
                    <td><%= link_to('削除', chat_system_authentication_token_path(token), method: :delete, class: 'btn btn-danger') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= link_to('連携用トークンを生成する', new_chat_system_authentication_token_path, class: 'btn btn-success') %>
            <p>チャットシステムで、連携したいサーバの任意のチャンネルで、`.confirm トークン` というコマンドを発言します。</p>
          </div>

          <div>
            <h2>有効なメール認証用トークン</h2>
            <table class="table table-striped table-responsive">
              <thead>
                <tr>
                  <th>チャット環境</th>
                  <th>トークン</th>
                  <th>有効期限</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @user.chat_system_authentication_mails.each do |token| %>
                  <tr>
                    <td><%= token.chat_system.name %></td>
                    <td><input type="text" value="<%= token.token %>"></td>
                    <td><%= token.expire_at %></td>
                    <td>
                      <%= link_to('連携', chat_system_links_path(token.token), class: 'btn btn-success') %>
                      <%= link_to('削除', chat_system_authentication_mail_path(token), method: :delete, class: 'btn btn-danger') %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <%= render('shared/description_token') %>
        </div>
      </div>
    </div>
  </div>
</div>